export const doctors = [
  {
    id: 1,
    name: "Dr. Ada Loveyou",
    specialty: "OB-GYN",
    patients: 18,
    status: "Active",
    email: "ada.loveyou@kalingahealth.org",
    phone: "+63 917 555 1234",
    address: "Brgy. San Isidro, Metro Manila",
    licenseNumber: "PH-789654",
    experienceYears: 12,
    clinic: "Kalinga Women's Clinic",
  },
  {
    id: 2,
    name: "Dr. Maria Santos",
    specialty: "Pediatrics",
    patients: 22,
    status: "Active",
    email: "maria.santos@kalingahealth.org",
    phone: "+63 917 555 2345",
    address: "Brgy. Malinis, Quezon City",
    licenseNumber: "PH-456321",
    experienceYears: 8,
    clinic: "Little Care Pediatrics",
  },
  {
    id: 3,
    name: "Dr. Mark Reyes",
    specialty: "Cardiology",
    patients: 14,
    status: "Inactive",
    email: "mark.reyes@kalingahealth.org",
    phone: "+63 917 555 3456",
    address: "Brgy. Kanluran, Pasay City",
    licenseNumber: "PH-321987",
    experienceYears: 15,
    clinic: "HeartLine Cardiology Center",
  },
  {
    id: 4,
    name: "Dr. Jane Cruz",
    specialty: "Dentistry",
    patients: 10,
    status: "Active",
    email: "jane.cruz@kalingahealth.org",
    phone: "+63 917 555 4567",
    address: "Brgy. Batis, Makati City",
    licenseNumber: "PH-654789",
    experienceYears: 7,
    clinic: "Smiles Dental Care",
  },
  {
    id: 5,
    name: "Dr. Leo Mendoza",
    specialty: "Orthopedics",
    patients: 12,
    status: "Active",
    email: "leo.mendoza@kalingahealth.org",
    phone: "+63 917 555 5678",
    address: "Brgy. Baybayin, Pasig City",
    licenseNumber: "PH-852963",
    experienceYears: 11,
    clinic: "Kalinga Orthopedics Clinic",
  },
  {
    id: 6,
    name: "Dr. Mia dela Cruz",
    specialty: "Dermatology",
    patients: 8,
    status: "Inactive",
    email: "mia.delacruz@kalingahealth.org",
    phone: "+63 917 555 6789",
    address: "Brgy. Silungan, Taguig City",
    licenseNumber: "PH-159753",
    experienceYears: 9,
    clinic: "Dermacare Studio",
  },
]

export function getDoctors() {
  return new Promise((resolve) => {
    setTimeout(() => resolve(doctors), 300)
  })
}
