export const patientsData = [
  {
    id: 1,
    name: "Leonor Rivera",
    gender: "Female",
    age: 34,
    patients: 18,
    status: "Active",
    email: "leonor.rivera@gmail.com",
    phone: "0917-111-2233",
    address: "123 Rizal St., Manila",
    bloodType: "A+",
    doctor: "Dr. Ada Loveyou",
    lastVisit: "05/10/2026",
    condition: "Hypertension",
  },
  {
    id: 2,
    name: "Enchong Dee",
    gender: "Male",
    age: 29,
    patients: 27,
    status: "Active",
    email: "enchong.dee@gmail.com",
    phone: "0918-222-3344",
    address: "456 Mabini Ave., Quezon City",
    bloodType: "O+",
    doctor: "Dr. Lenard Panganiban",
    lastVisit: "05/12/2026",
    condition: "Diabetes Type 2",
  },
  {
    id: 3,
    name: "Austin Reaves",
    gender: "Male",
    age: 25,
    patients: 33,
    status: "Inactive",
    email: "austin.reaves@gmail.com",
    phone: "0919-333-4455",
    address: "789 Del Pilar St., Batangas",
    bloodType: "B+",
    doctor: "Dr. Kwak Kwak",
    lastVisit: "03/05/2026",
    condition: "Asthma",
  },
  {
    id: 4,
    name: "Niana Guererro",
    gender: "Female",
    age: 22,
    patients: 22,
    status: "Active",
    email: "niana.g@gmail.com",
    phone: "0920-444-5566",
    address: "321 Bonifacio Blvd., Lipa",
    bloodType: "AB+",
    doctor: "Dr. Ada Loveyou",
    lastVisit: "05/15/2026",
    condition: "Anemia",
  },
  {
    id: 5,
    name: "Kendall Jenner",
    gender: "Female",
    age: 28,
    patients: 29,
    status: "Active",
    email: "kendall.j@gmail.com",
    phone: "0921-555-6677",
    address: "654 Luna St., Tanauan",
    bloodType: "O-",
    doctor: "Dr. Jose Rizal",
    lastVisit: "05/18/2026",
    condition: "Migraine",
  },
  {
    id: 6,
    name: "Justin Bieber",
    gender: "Male",
    age: 30,
    patients: 31,
    status: "Active",
    email: "justin.b@gmail.com",
    phone: "0922-666-7788",
    address: "987 Aguinaldo Rd., Cavite",
    bloodType: "A-",
    doctor: "Dr. Kwek Kwek",
    lastVisit: "05/19/2026",
    condition: "Lyme Disease",
  },
  {
    id: 7,
    name: "Megan Fox",
    gender: "Female",
    age: 37,
    patients: 36,
    status: "Active",
    email: "megan.fox@gmail.com",
    phone: "0923-777-8899",
    address: "147 Lawton Ave., Manila",
    bloodType: "B-",
    doctor: "Dr. Ada Loveyou",
    lastVisit: "05/20/2026",
    condition: "Thyroid Disorder",
  },
]

export const patientSummary = [
  { label: "Total Patients",    value: 567 },
  { label: "Active Patients",   value: 167 },
  { label: "Inactive Patients", value: 7   },
  { label: "New This Month",    value: 10  },
]

export function getPatients() {
  return new Promise((resolve) => {
    setTimeout(() => resolve(patientsData), 300)
  })
}